# Generated by Django 4.2.7 on 2023-12-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="image.jpg", upload_to="image/%Y", verbose_name="Изображение"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(verbose_name="Дата публекации"),
        ),
    ]
